apiVersion: apps/v1
kind: Deployment
metadata:
  name: discharge-service
  namespace: f21ao-namespace
  
spec:
  replicas: 2  # Number of replicas
  selector:
    matchLabels:
      app.kubernetes.io/name: discharge-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: discharge-service
    spec:
      containers:
        - name: discharge-service
          image: bhagya95/f21ao-group7-discharge-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: DISCHARGE_DB_URI
              valueFrom:
                secretKeyRef:
                  name: discharge-service-secret
                  key: DISCHARGE_DB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: discharge-service-secret
                  key: JWT_SECRET
            - name: DISCHARGE_PORT
              valueFrom:
                configMapKeyRef:
                  name: discharge-service-config
                  key: DISCHARGE_PORT
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: discharge-service-config
                  key: AUTH_SERVICE_URL
            - name: PATIENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: discharge-service-config
                  key: PATIENT_SERVICE_URL
            - name : DISCHARGE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: discharge-service-config
                  key: DISCHARGE_BASE_URL

                