apiVersion: apps/v1
kind: Deployment
metadata:
  name: treatment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: treatment-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: treatment-service
    spec:
      containers:
        - name: treatment-service
          image: bhagya95/treatment-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: URI
              valueFrom:
                secretKeyRef:
                  name: treatment-service-secret
                  key: URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: treatment-service-secret
                  key: JWT_SECRET
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: treatment-service-config
                  key: PORT
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: treatment-service-config
                  key: AUTH_SERVICE_URL
            - name: PATIENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: treatment-service-config
                  key: AUTH_SERVICE_URL

                