services:
  authentication-service:
    #build: ./Authentication-Service
    image: harika1601/f21ao-authentication-service:latest
    ports:
      - "3001:3001"
    env_file:
      - ./Authentication-Service/.env
    restart: unless-stopped
    networks:
      - hospital-network

  patient-service:
    #build: ./PatientRegistration-Service
    image: harika1601/f21ao-patient-service:latest
    ports:
      - "3002:3002"
    env_file:
      - ./PatientRegistration-Service/.env
    depends_on:
      - authentication-service
    restart: unless-stopped
    networks:
      - hospital-network

  discharge-service:
    #build: ./Discharge-Service
    image: harika1601/f21ao-discharge-service:latest
    ports:
      - "3003:3003"
    env_file:
      - ./Discharge-Service/.env
    depends_on:
      - patient-service
      - authentication-service
    restart: unless-stopped
    networks:
      - hospital-network

  treatment-service:
    #build: ./Treatment-service
    image: harika1601/f21ao-treatment-service:latest
    ports:
      - "3004:3004"
    env_file:
      - ./Treatment-service/.env
    depends_on:
      - authentication-service
      - patient-service
    restart: unless-stopped
    networks:
      - hospital-network

networks:
  hospital-network:
    driver: bridge