services:
  authentication-service:
    image: bhagya95/Authentication-Service
    ports:
      - "3001:3001"
    env_file:
      - ./Authentication-Service/.env
    restart: unless-stopped
    networks:
      - hospital-network

  patient-service:
    image: bhagya95/PatientRegistration-Service
    ports:
      - "3002:3002"
    env_file:
      - ./PatientRegistration-Service/.env
    depends_on:
      - authentication-service
    restart: unless-stopped
    networks:
      - hospital-network

  discharge-service:
    image: bhagya95/Discharge-Service
    ports:
      - "3003:3003"
    env_file:
      - ./Discharge-Service/.env
    depends_on:
      - patient-service
      - authentication-service
    restart: unless-stopped
    networks:
      - hospital-network

  treatment-service:
    image: bhagya95/Treatment-service
    ports:
      - "3004:3004"
    env_file:
      - ./Treatment-service/.env
    depends_on:
      - authentication-service
      - patient-service
    restart: unless-stopped
    networks:
      - hospital-network

networks:
  hospital-network:
    driver: bridge
