apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: patient-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: patient-service
    spec:
      containers:
        - name: patient-service
          image: harika1601/f21ao-patient-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: URI
              valueFrom:
                secretKeyRef:
                  name: patient-service-secret
                  key: URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: patient-service-secret
                  key: JWT_SECRET
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: patient-service-config
                  key: PORT
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: patient-service-config
                  key: AUTH_SERVICE_URL
            - name : BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: patient-service-config
                  key: BASE_URL

                