apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app.kubernetes.io/name: authentication-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: NodePort
