apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 2  # Number of replicas (adjust as needed)
  selector:
    matchLabels:
      app.kubernetes.io/name: authentication-service  # Ensure this matches the label in the pod template
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authentication-service  # Same label as the selector
    spec:
      containers:
        - name: authentication-service
          image: bhagya95/authentication-service:latest  # Replace with your Docker Hub image
          ports:
            - containerPort: 3001
          env:
            - name: URI
              valueFrom:
                secretKeyRef:
                  name: authentication-service-secret
                  key: URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: authentication-service-secret
                  key: JWT_SECRET
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: authentication-service-config
                  key: PORT
